### ISSUE TITLE
Unknown MAT file type

### ISSUE THREAD

**Issue by arnavmehta7** [aczajka/iris-recognition---pm-diseased-human-driven-bsif#3]
`  File "/home/user/Desktop/CODE/Python/IRIS_RECOG/iris-recognition---pm-diseased-human-driven-bsif/src-python/modules/irisRecognition.py", line 34, in __init__
    self.filter = scipy.io.loadmat(cfg["recog_bsif_dir"]+'ICAtextureFilters_{0}x{1}_{2}bit.mat'.format(self.filter_size, self.filter_size, self.num_filters))['ICAtextureFilters']
  File "/home/user/Desktop/CODE/Python/ai_env/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 225, in loadmat
    MR, _ = mat_reader_factory(f, **kwargs)
  File "/home/user/Desktop/CODE/Python/ai_env/lib/python3.8/site-packages/scipy/io/matlab/_mio.py", line 74, in mat_reader_factory
    mjv, mnv = _get_matfile_version(byte_stream)
  File "/home/user/Desktop/CODE/Python/ai_env/lib/python3.8/site-packages/scipy/io/matlab/_miobase.py", line 251, in _get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 49, 50
`
I am getting above error whenever I am trying to run the code, can you please tell what's wrong?

**Comment by Annamalai-S** [comment]
Same issue. Someone help with this issue

**Comment by Siamul** [comment]
Hello, this issue is usually due to .mat files being incorrectly downloaded when using git clone if you don't have git-lfs installed. The solution is mentioned in the "Troubleshooting" section of the readme. Please download the mat files from this link: https://drive.google.com/drive/folders/1pyifeABdRUQZWfjMEB0f0ye8h1K2qNDO?usp=sharing , that should fix the issue.

**Comment by Annamalai-S** [comment]
Thanks for the help dude.
Could this project be used to differentiate dead and alive person eye??

I'm a noob in python could you help me to learn Deep Learning with
        - the roadmap
        - the resources you used
